### ISSUE TITLE
ios9 / iPod touch / CCLabelTTF enableShadow 导致整个标签不显示

### ISSUE THREAD

**Issue by airkraken** [stubma/cocos2dx-classical#3]
`label->enableShadow(CCSizeMake(2.5, -2.5), 0xff333333, 1);`

导致整个标签不显示，请看看是怎么回事，谢谢。

**Comment by stubma** [comment]
这几天改了一下这块的逻辑, 现在stroke支持外描边了, enableShadow测了一下应该无问题了. HelloLua里面加了CCLabelTTF的演示, 可以看一下.

**Comment by airkraken** [comment]
我pull了代码，试了一下，还是不显示。CCLabelTTF是放在CCCLippingNode里的，和这个有关吗？

**Comment by stubma** [comment]
那就先别放在clipping里面试一下

**Comment by airkraken** [comment]
我试了下，直接放在layer里，打开阴影以后，还是不显示。不打开就正常显示。

**Comment by stubma** [comment]
知道原因了, 已修正
