### ISSUE TITLE
好久不见

### ISSUE THREAD

**Issue by zcgit** [stubma/cocos2dx-classical#8]
Hi，不知道对我还有没有印象？从最开始关注到你的cocos2dx-better之后就一直会定期查看下您的更新，从您的代码里学到了很多东西，无论是技术上的还是专业性上的，对我而言都是受益匪浅，在这里真诚地表示感谢。
  从您的主页我也了解到了wiyun这个引擎和公司，对该引擎的完成度以及推出时间表示震撼，我不知道这是多少人完成的，但我觉得在那个时期能做出这样的已经很不错了，无论成败，我对这个引擎还是持赞赏态度的，并且也从中学习到不少有价值的东西，再次表示感谢。
  我注意到您一直在持续更新维护代码，个人猜测您应该也是在不断做游戏不断发现并解决问题，有时也会期待玩到您的游戏或知晓哪款游戏是您的。
  我个人这几年也一直参与游戏研发，也带过项目，但才疏学浅，未能作出值得夸耀的好成绩。
  在我印象中，我好像去过微云公司面试过，那是2011年，我记得地址在知春路，现在的腾讯视频那里，不知道对不对？

**Comment by stubma** [comment]
对, 原来你还来过, 不记得你是谁了, id是认得的. 目前一直做游戏, 也没什么可以吹的, 说多了都是泪. 游戏成功不成功要看团队要看运气, 技术狗表示这都是命.
