### ISSUE TITLE
文字问题

### ISSUE THREAD

**Issue by zcgit** [stubma/cocos2dx-classical#9]
cocos2d-x的文字一直存在的问题，无论是2.x还是3.x都会有模糊的情况，问题描述可以参考下https://github.com/cocos2d/cocos2d-x/issues/13699，        对此您有什么看法，我看到3.x的用了freetype比2.x的要好一点，但还是没解决问题？

**Comment by stubma** [comment]
我觉得这种情况先换个字体试试, 把那个游戏的字体文件弄出来试试.

**Comment by zcgit** [comment]
和字体本身关系不太大，换成系统字同样会不清晰。

**Comment by stubma** [comment]
13699里说用set alias, 有用吗

**Comment by zcgit** [comment]
没有用，我试过很多种方式没用，cocos2dx-classical里的文字也会模糊的，有时候反而比较明显，因为她的方式是native生成bitmap，再转成texture，这个过程中会涉及到屏幕适配的拉伸处理，所以也会存在模糊的现象，另外，我发现市面上绝大多数用cocos2dx的文字都会模糊，除了网易游戏以外。

**Comment by stubma** [comment]
这样的话, 那我肯定先把梦幻西游里面的字体文件弄出来试一下, 你试过没有, 没试过的话建议你先试试. 我觉得和字体也是可能有关系的, 比如少年三国志的字体, 我用着就不觉得模糊.
